### ISSUE TITLE
Port to Godot 4

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/godot-donut-collision-polygon-2d#2]
@Deozaan has made a fork for Godot 4, however this fork doesn't have the latest changes of the plugin

If possible, merge that fork to release a single version with all the contributions for Godot 4, if not, branch for version 4 and add it as a different plugin

**Comment by angrykoala** [comment]
Any input on this from you @Deozaan?

**Comment by Deozaan** [comment]
The only reason I made my fork was because I needed a version for Godot 4.x and I saw the last update to this repository was quite some time ago so I assumed it was no longer being maintained. I realize now I should have made a pull request or opened an issue. 😅

I'd be happy to relinquish my fork and related Asset Library submission back to you for a single, authoritative repository containing both the Godot 3.x and 4.x versions of this plugin.

What do you need from me to make it happen?

**Comment by angrykoala** [comment]
Hey @Deozaan  Thanks for coming back to me

No worries, it is an open source project and I'm glad someone was keeping it alive :). Obviously you are free to maintain the fork if you prefer. My only worry about the asset library is making people confused about multiple versions, but again, your call.

I think a pull request would be ideal, so we keep all contributions on the repo and in the published version if that sounds good to you

Than

**Comment by Deozaan** [comment]
I'm willing to submit a PR but I could use some guidance. How do you want to handle separation between Godot 3.x and 4.x? In my fork I ditched 3.x compatibility and only concerned myself with getting it to work in Godot 4.x. Do you want me to put my work in a separate branch, or in a separate (sub)folder, or...?

I'm also not sure how to delete or turn over my Asset Library submission to you. But I suppose that could be sorted out with an email to the appropriate person after we consolidate both versions over here.

**Comment by angrykoala** [comment]
I think we can make 2 branches maybe? Or a new folder? What do you think? @Deozaan

**Comment by Deozaan** [comment]
I'll just put it into a separate branch. That way it should maintain a clear separation between the two versions.

**Comment by Deozaan** [comment]
@angrykoala I think you will have to create a branch in this repository before I can submit a PR to that new branch.

**Comment by angrykoala** [comment]
Hey @Deozaan 

Thanks for your help. Sorry it took me a while to come back to you. I've checked how the release process is for godot and it seems it doesn't really support branches, so I created a release and pinned the current commit for the existing Godot 3 library

Feel free to open a PR to `master`, as that's where version 4 will live.

Regarding how to solve the situation of the Godot asset library, I have no clue tbh. I agree that an email may solve it. Another option is to update the README pointing to the new version.

It wouldn't be a good experience for users to click on the asset and find that the repo doesn't exists, so I'd' say that better to keep your fork as well in the meantime (again, you are free to keep the fork and the listing asset if you want).

**Comment by Deozaan** [comment]
> Feel free to open a PR to `master`, as that's where version 4 will live.

Done.

> Regarding how to solve the situation of the Godot asset library, I have no clue tbh. I agree that an email may solve it. Another option is to update the README pointing to the new version.

I've opened an issue on the Godot Asset Library tracker asking to transfer my submission to you or delete it so you can open a new one for the Godot 4.x port.

**Comment by Deozaan** [comment]
While waiting for a response to godotengine/godot-asset-library#329 I have in the meantime submitted an update to my Asset Library submission, pointing to the latest version in this repository.

**Comment by angrykoala** [comment]
Thanks @Deozaan 

I think this issue can be considered completed. It may be a bit messy for end users because we have now 2 assets in the godot library but at least both will work

* https://godotengine.org/asset-library/asset/2163
* https://godotengine.org/asset-library/asset/2992

I'm unsure of the consequences of deleting an asset from the store. I think the files are completely downloaded without a link or dependency so it should be fine
